// iox — ops.h: one include for every operation.
#pragma once

#include "iox/ops/accept.h"
#include "iox/ops/close.h"
#include "iox/ops/connect.h"
#include "iox/ops/fsync.h"
#include "iox/ops/open.h"
#include "iox/ops/poll.h"
#include "iox/ops/read.h"
#include "iox/ops/read_at.h"
#include "iox/ops/recv_from.h"
#include "iox/ops/schedule.h"
#include "iox/ops/send_to.h"
#include "iox/ops/signal.h"
#include "iox/ops/splice.h"
#include "iox/ops/tee.h"
#include "iox/ops/timer.h"
#include "iox/ops/wait_pid.h"
#include "iox/ops/write.h"
#include "iox/ops/write_at.h"
